---
services:
  wassf__dashy:
    image: lissy93/dashy
    container_name: wassf__dashy
    volumes:
      - ./dashboard/dashy/user-data/conf.yml:/app/user-data/conf.yml
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - wassf__fastapi
      - wassf__aiogram

  wassf__fastapi:
    build:
      context: ./services/docs/fastapi
    container_name: wassf__fastapi
    ports:
      - 8300:8300
    restart: unless-stopped

  wassf__aiogram:
    build:
      context: ./services/docs/aiogram
    container_name: wassf__aiogram
    ports:
      - 8989:8989
    restart: unless-stopped
---
services:
  wassf__grafana:
    # image: docker run -d -p 3000:3000 --name grafana grafana/grafana-enterprise:<version number>
    image: grafana/grafana-enterprise
    container_name: wassf__grafana
    volumes:
      - ./visualization/grafana/custom.ini:/usr/share/grafana/conf/custom.ini
    ports:
      - 3000:3000
    restart: unless-stopped
